import { type KnipConfig } from "knip";

const config: KnipConfig = {
	// Generated by Claude design export; not part of any build graph.
	ignore: ["design/**"],
	ignoreIssues: {
		// Ignoring the bedrock files below also hides the sole import of
		// `ApplicationError`: `TextGenerationError` extends it, and nothing
		// else in the repository references it.
		"apps/backend/src/libs/exceptions/exceptions.ts": ["exports"],
		// `SchemaKey` is the entry point for structured generation, which has no
		// caller yet: label generation uses `generateText` (#96).
		"apps/backend/src/libs/modules/generator/generator.ts": ["exports"],
		// `PromptEmbeddingSource` and `NearestPrompt` are exported ahead of their
		// consumers: the editing flow (regenerate) and search (#77).
		"apps/backend/src/modules/prompt-embeddings/prompt-embeddings.ts": [
			"types",
		],
		// Public contracts of the shared package. These predate the RTK Query
		// migration and are published for consumers that do not exist yet.
		"packages/shared/src/**": ["exports", "types"],
	},
	prettier: ["./prettier.config.js"],
	stylelint: ["./stylelint.config.ts"],
	workspaces: {
		".": {},
		"apps/backend": {
			entry: ["src/db/migrations/*.ts"],
			// knex resolves its driver at runtime from `DB_DIALECT`, so nothing
			// imports `pg`; removing it makes knex throw on the first connection.
			ignoreDependencies: ["pg"],
		},
		"apps/frontend": {},
		"apps/mcp": {},
		"packages/shared": {
			includeEntryExports: true,
		},
	},
};

export default config;
