const MINIMUM_WORKSPACE_COUNT_FOR_DELETION = 2;
const TOP_ACTIVITY_DAYS = 7;
const WORKSPACE_OWNER_COUNT = 1;

export {
	MINIMUM_WORKSPACE_COUNT_FOR_DELETION,
	TOP_ACTIVITY_DAYS,
	WORKSPACE_OWNER_COUNT,
};
