const AnalyticLabel = {
	DESCRIPTION:
		"Every scored prompt re-weights the index. This is what those weights look like right now: which tiers your prompts land in, which keywords carry weight, and how fast the system is getting better.",
	DISTRIBUTION_TITLE: "Efficiency distribution",
	DISTRIBUTION_TOTAL_MANY: "scored prompts in scope",
	DISTRIBUTION_TOTAL_ONE: "scored prompt in scope",
	EMPTY_SCOPE: "No scored prompts in this scope yet",
	EMPTY_VALUE: "-",
	GLOBAL_SCOPE_OPTION: "Global base (all workspaces)",
	GROWTH_CHANGE: "Range change",
	GROWTH_DESCRIPTION_FROM: "Average score went from",
	GROWTH_DESCRIPTION_NO_TREND: "No continuous trend yet, latest average score",
	GROWTH_DESCRIPTION_OVER: "over the last",
	GROWTH_DESCRIPTION_TO: "to",
	GROWTH_EMPTY: "Not enough data yet",
	GROWTH_EMPTY_REASON: "No prompts were scored in the last",
	GROWTH_FIELD: "Growth range",
	GROWTH_FIRST: "First",
	GROWTH_LATEST: "Latest",
	GROWTH_RANGE_PREFIX: "Last",
	GROWTH_TITLE: "System intelligence growth",
	GROWTH_TREND_HINT_PREFIX: "Needs two consecutive scored",
	GROWTH_TREND_HINT_SUFFIX: "to show a trend.",
	KEYWORD_PREFIX: "#",
	KEYWORDS_DESCRIPTION:
		"Average score of every scored prompt carrying the tag, and how many carry it.",
	KEYWORDS_EMPTY: "No keywords yet",
	KEYWORDS_TITLE: "Keyword performance weights",
	KICKER: "Intelligence",
	KPI_AVERAGE_CAPTION: "/ 10",
	KPI_AVERAGE_LABEL: "Avg efficiency",
	KPI_CHANGE_CAPTION_PREFIX: "from",
	KPI_CHANGE_LABEL: "Weekly change",
	KPI_KEYWORDS_CAPTION: "parsed tags",
	KPI_KEYWORDS_LABEL: "Keywords weighted",
	KPI_SCORED_CAPTION: "in scope",
	KPI_SCORED_LABEL: "Scored prompts",
	KPI_SECTION: "Summary metrics",
	LOAD_ERROR: "Failed to load analytics. Please try again.",
	SCOPE_FIELD: "Scope",
	TITLE: "Data intelligence",
} as const;

export { AnalyticLabel };
