const GrowthChartConfig = {
	AXIS_PRECISION: 2,
	DOT_RADIUS: 4,
	FALLBACK_AXIS_STEP: 5,
	FLAT_RANGE_PADDING: 1,
	HEIGHT: 260,
	INDEX_OFFSET: 1,
	LABEL_GAP: 8,
	MAX_AXIS_INTERVALS: 4,
	MIN_SCORED_POINTS: 1,
	MIN_TREND_POINTS: 2,
	PADDING_BOTTOM: 28,
	PADDING_LEFT: 40,
	PADDING_RIGHT: 16,
	PADDING_TOP: 12,
	PATH_PRECISION: 1,
	SINGLE_POINT: 1,
	TICK_COUNT_OFFSET: 1,
	WIDTH: 720,
	X_LABEL_OFFSET: 18,
} as const;

export { GrowthChartConfig };
