const PromptHistoryLabel = {
	ANY_SCORE: "Any score",
	AVERAGE_SCORE: "Average score",
	CLEAR: "Clear",
	COPY_PROMPT: "Copy prompt",
	EFFICIENCY_SCORE: "Efficiency score",
	EMPTY_FILTERS: "No prompts match the current filters.",
	EMPTY_NO_WORKSPACES: "Create a workspace to browse prompts.",
	EMPTY_SELECTION: "Select a result to read the full prompt.",
	EMPTY_WORKSPACE: "No prompts in this workspace yet.",
	EYEBROW: "Smart search",
	HINT_BROWSE: "Showing this workspace's prompt history.",
	HINT_SEARCH:
		"Match describes relevance; quality reflects the recorded outcome.",
	LOAD_ERROR: "Failed to load prompts. Please try again.",
	LOAD_MORE: "Load More",
	LOADING: "Loading...",
	OPEN_FULL_PAGE: "Open full page",
	PROMPTS_LOGGED: "Prompts logged",
	QUALITY_TIER: "Quality Tier",
	QUALITY_TIER_ALL: "Any quality",
	QUALITY_TIER_NEEDS_IMPROVEMENT: "Needs Improvement (1-5.9)",
	QUALITY_TIER_PROVEN: "Proven (8-10)",
	QUALITY_TIER_UNRATED: "Unrated",
	QUALITY_TIER_USABLE: "Usable (6-7.9)",
	RESULT: "result",
	RESULTS: "results",
	RETRY: "Retry",
	SEARCH: "Describe the task",
	SEARCH_PLACEHOLDER:
		"Describe the task: “rate limit middleware”, “stripe webhook”…",
	SUBTITLE: "Find the prompt that already worked",
	TASK_INTENT: "Task Intent",
	WORKSPACE: "Workspace",
} as const;

export { PromptHistoryLabel };
