const DIGEST_ALGORITHM = "sha256";

const NO_ROWS_DELETED = 0;

const SECRET_BYTE_LENGTH = 32;

const SECRET_ENCODING = "hex";

const TOKEN_PARTS_LIMIT = 2;

export {
	DIGEST_ALGORITHM,
	NO_ROWS_DELETED,
	SECRET_BYTE_LENGTH,
	SECRET_ENCODING,
	TOKEN_PARTS_LIMIT,
};
