import { MILLISECONDS_PER_MINUTE } from "~/libs/constants/constants.js";

const LAST_USED_THROTTLE_MINUTES = 5;

const LAST_USED_THROTTLE_MS =
	LAST_USED_THROTTLE_MINUTES * MILLISECONDS_PER_MINUTE;

export { LAST_USED_THROTTLE_MS };
