const MILLISECONDS_PER_MINUTE = 60_000;

const LAST_USED_THROTTLE_MINUTES = 5;

const LAST_USED_THROTTLE_MS =
	LAST_USED_THROTTLE_MINUTES * MILLISECONDS_PER_MINUTE;

export { LAST_USED_THROTTLE_MS };
