const ErrorCode = {
	AUTH_EMAIL_ALREADY_EXISTS: "AUTH_EMAIL_ALREADY_EXISTS",
	AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
	FORBIDDEN: "FORBIDDEN",
	INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
	NOT_FOUND: "NOT_FOUND",
	UNAUTHENTICATED: "UNAUTHENTICATED",
	VALIDATION_FAILED: "VALIDATION_FAILED",
} as const;

export { ErrorCode };
