const ServerErrorCode = {
	FORBIDDEN: "FORBIDDEN",
	INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
	NOT_FOUND: "NOT_FOUND",
	TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
	UNAUTHENTICATED: "UNAUTHENTICATED",
	VALIDATION_FAILED: "VALIDATION_FAILED",
} as const;

export { ServerErrorCode };
