const FIRST_RETRY_DELAY_MS = 5000;

const SECOND_RETRY_DELAY_MS = 15_000;

const PROVISION_RETRY_DELAYS_MS = [
	FIRST_RETRY_DELAY_MS,
	SECOND_RETRY_DELAY_MS,
] as const;

export { PROVISION_RETRY_DELAYS_MS };
