import { type Knex } from "knex";

const TABLE_NAME = "workspaces";
const NO_DROPPED_TAGS = 0;
const NO_ROWS = 0;
const BATCH_SIZE = 500;
const FIRST_ID = 0;
const LAST_INDEX = -1;

const ColumnName = {
	DROPPED_STACK_TAGS: "dropped_stack_tags",
	ID: "id",
	STACK_TAGS: "stack_tags",
	UPDATED_AT: "updated_at",
} as const;

type NormalizeResult = {
	droppedTags: string[];
	normalizedTags: string[];
};

type WorkspaceRow = {
	[ColumnName.DROPPED_STACK_TAGS]: null | string[];
	[ColumnName.ID]: number;
	[ColumnName.STACK_TAGS]: null | string[];
	[ColumnName.UPDATED_AT]: string;
};

const VARIANT_TO_CANONICAL: Record<string, string> = {
	"adonis": "AdonisJS",
	"adonisjs": "AdonisJS",
	"ADONISJS": "AdonisJS",
	"alpine": "Alpine.js",
	"alpine.js": "Alpine.js",
	"alpinejs": "Alpine.js",
	"ALPINEJS": "Alpine.js",
	"amazon web services": "AWS",
	"amqp": "AMQP",
	"AMQP": "AMQP",
	"android": "Android",
	"ANDROID": "Android",
	"angular": "Angular",
	"ANGULAR": "Angular",
	"AngularJS": "Angular",
	"angularjs": "Angular",
	"ansible": "Ansible",
	"ANSIBLE": "Ansible",
	"argo": "ArgoCD",
	"argocd": "ArgoCD",
	"ARGOCD": "ArgoCD",
	"asp.net": "ASP.NET Core",
	"asp.net core": "ASP.NET Core",
	"aspnetcore": "ASP.NET Core",
	"ASPNETCORE": "ASP.NET Core",
	"astro": "Astro",
	"ASTRO": "Astro",
	"aws": "AWS",
	"AWS": "AWS",
	"axios": "Axios",
	"AXIOS": "Axios",
	"azure": "Azure",
	"AZURE": "Azure",
	"babel": "Babel",
	"BABEL": "Babel",
	"bun": "Bun",
	"BUN": "Bun",
	"c#": "C#",
	"c++": "C++",
	"c-sharp": "C#",
	"capacitor": "Capacitor",
	"CAPACITOR": "Capacitor",
	"cassandra": "Cassandra",
	"CASSANDRA": "Cassandra",
	"chai": "Chai",
	"CHAI": "Chai",
	"chart": "Chart.js",
	"chart.js": "Chart.js",
	"chartjs": "Chart.js",
	"CHARTJS": "Chart.js",
	"chef": "Chef",
	"CHEF": "Chef",
	"circle": "CircleCI",
	"circleci": "CircleCI",
	"CIRCLECI": "CircleCI",
	"click": "ClickHouse",
	"clickhouse": "ClickHouse",
	"CLICKHOUSE": "ClickHouse",
	"clojure": "Clojure",
	"CLOJURE": "Clojure",
	"cordova": "Cordova",
	"CORDOVA": "Cordova",
	"cplusplus": "C++",
	"cpp": "C++",
	"CPP": "C++",
	"CS": "C#",
	"csharp": "C#",
	"css-modules": "CSS Modules",
	"cssmodules": "CSS Modules",
	"CSSMODULES": "CSS Modules",
	"cypress": "Cypress",
	"CYPRESS": "Cypress",
	"d3": "D3.js",
	"d3.js": "D3.js",
	"d3js": "D3.js",
	"D3JS": "D3.js",
	"datadog": "Datadog",
	"DATADOG": "Datadog",
	"date-fns": "date-fns",
	"datefns": "date-fns",
	"DATEFNS": "date-fns",
	"deno": "Deno",
	"DENO": "Deno",
	"django": "Django",
	"DJANGO": "Django",
	"docker": "Docker",
	"DOCKER": "Docker",
	"docker container": "Docker",
	"dotnet core": "ASP.NET Core",
	"drizzle": "Drizzle",
	"DRIZZLE": "Drizzle",
	"dynamo": "DynamoDB",
	"dynamodb": "DynamoDB",
	"DYNAMODB": "DynamoDB",
	"effector": "Effector",
	"EFFECTOR": "Effector",
	"elastic": "Elasticsearch",
	"elasticsearch": "Elasticsearch",
	"ELASTICSEARCH": "Elasticsearch",
	"elixir": "Elixir",
	"ELIXIR": "Elixir",
	"emotion": "Emotion",
	"EMOTION": "Emotion",
	"es": "Elasticsearch",
	"esbuild": "esbuild",
	"ESBUILD": "esbuild",
	"express": "Express.js",
	"express.js": "Express.js",
	"expressjs": "Express.js",
	"EXPRESSJS": "Express.js",
	"fast-api": "FastAPI",
	"fastapi": "FastAPI",
	"FASTAPI": "FastAPI",
	"fastify": "Fastify",
	"FASTIFY": "Fastify",
	"firebasefirestore": "Firebase Firestore",
	"FIREBASEFIRESTORE": "Firebase Firestore",
	"firestore": "Firebase Firestore",
	"flask": "Flask",
	"FLASK": "Flask",
	"flutter": "Flutter",
	"FLUTTER": "Flutter",
	"framer": "Framer Motion",
	"framermotion": "Framer Motion",
	"FRAMERMOTION": "Framer Motion",
	"gatsby": "Gatsby",
	"GATSBY": "Gatsby",
	"gcp": "GCP",
	"GCP": "GCP",
	"gh-actions": "GitHub Actions",
	"githubactions": "GitHub Actions",
	"GITHUBACTIONS": "GitHub Actions",
	"gitlab-ci": "GitLab CI",
	"gitlabci": "GitLab CI",
	"GITLABCI": "GitLab CI",
	"go": "Go",
	"golang": "Go",
	"GOLANG": "Go",
	"google cloud": "GCP",
	"google cloud platform": "GCP",
	"grafana": "Grafana",
	"GRAFANA": "Grafana",
	"graph-ql": "GraphQL",
	"graphql": "GraphQL",
	"GRAPHQL": "GraphQL",
	"grpc": "gRPC",
	"GRPC": "gRPC",
	"gsap": "GSAP",
	"GSAP": "GSAP",
	"haskell": "Haskell",
	"HASKELL": "Haskell",
	"helm": "Helm",
	"HELM": "Helm",
	"html": "HTML",
	"HTML": "HTML",
	"htmx": "HTMX",
	"HTMX": "HTMX",
	"i18next": "i18next",
	"I18NEXT": "i18next",
	"influx": "InfluxDB",
	"influxdb": "InfluxDB",
	"INFLUXDB": "InfluxDB",
	"ionic": "Ionic",
	"IONIC": "Ionic",
	"ios": "iOS",
	"IOS": "iOS",
	"istio": "Istio",
	"ISTIO": "Istio",
	"jaeger": "Jaeger",
	"JAEGER": "Jaeger",
	"jasmine": "Jasmine",
	"JASMINE": "Jasmine",
	"java": "Java",
	"JAVA": "Java",
	"java8": "Java",
	"java11": "Java",
	"java17": "Java",
	"javascript": "JavaScript",
	"javascripts": "JavaScript",
	"jenkins": "Jenkins",
	"JENKINS": "Jenkins",
	"jest": "Jest",
	"JEST": "Jest",
	"joi": "Joi",
	"JOI": "Joi",
	"jotai": "Jotai",
	"JOTAI": "Jotai",
	"js": "JavaScript",
	"JS": "JavaScript",
	"k8s": "Kubernetes",
	"K8S": "Kubernetes",
	"kafka": "Kafka",
	"KAFKA": "Kafka",
	"karma": "Karma",
	"KARMA": "Karma",
	"knex": "Knex",
	"KNEX": "Knex",
	"koa": "Koa",
	"KOA": "Koa",
	"kotlin": "Kotlin",
	"KOTLIN": "Kotlin",
	"kubernetes": "Kubernetes",
	"kysely": "Kysely",
	"KYSELY": "Kysely",
	"laravel": "Laravel",
	"LARAVEL": "Laravel",
	"leaflet": "Leaflet",
	"LEAFLET": "Leaflet",
	"less": "LESS",
	"LESS": "LESS",
	"linkerd": "Linkerd",
	"LINKERD": "Linkerd",
	"lit": "Lit",
	"LIT": "Lit",
	"luxon": "Luxon",
	"LUXON": "Luxon",
	"mapbox": "Mapbox",
	"MAPBOX": "Mapbox",
	"maria": "MariaDB",
	"mariadb": "MariaDB",
	"MARIADB": "MariaDB",
	"matlab": "MATLAB",
	"MATLAB": "MATLAB",
	"microsoft azure": "Azure",
	"MICROSOFTSQLSERVER": "Microsoft SQL Server",
	"mobx": "MobX",
	"MOBX": "MobX",
	"mocha": "Mocha",
	"MOCHA": "Mocha",
	"mongo": "MongoDB",
	"mongodb": "MongoDB",
	"MONGODB": "MongoDB",
	"mongoose": "Mongoose",
	"MONGOOSE": "Mongoose",
	"mqtt": "MQTT",
	"MQTT": "MQTT",
	"mssql": "Microsoft SQL Server",
	"mysql": "MySQL",
	"MYSQL": "MySQL",
	"neo4": "Neo4j",
	"neo4j": "Neo4j",
	"NEO4J": "Neo4j",
	"nest": "NestJS",
	"nest-js": "NestJS",
	"nestjs": "NestJS",
	"NestJS": "NestJS",
	"NESTJS": "NestJS",
	"new-relic": "New Relic",
	"newrelic": "New Relic",
	"NEWRELIC": "New Relic",
	"next": "Next.js",
	"next-js": "Next.js",
	"next_js": "Next.js",
	"nextjs": "Next.js",
	"NextJS": "Next.js",
	"NEXTJS": "Next.js",
	"ng": "Angular",
	"node": "Node.js",
	"node-js": "Node.js",
	"nodejs": "Node.js",
	"NodeJS": "Node.js",
	"NODEJS": "Node.js",
	"np": "NumPy",
	"numpy": "NumPy",
	"NUMPY": "NumPy",
	"nuxt": "Nuxt.js",
	"nuxt-js": "Nuxt.js",
	"nuxtjs": "Nuxt.js",
	"NuxtJS": "Nuxt.js",
	"NUXTJS": "Nuxt.js",
	"opentelemetry": "OpenTelemetry",
	"otel": "OpenTelemetry",
	"OTEL": "OpenTelemetry",
	"panda": "Panda CSS",
	"pandacss": "Panda CSS",
	"PANDACSS": "Panda CSS",
	"parcel": "Parcel",
	"PARCEL": "Parcel",
	"pg": "PostgreSQL",
	"php": "PHP",
	"PHP": "PHP",
	"php7": "PHP",
	"php8": "PHP",
	"playwright": "Playwright",
	"PLAYWRIGHT": "Playwright",
	"postgres": "PostgreSQL",
	"Postgres": "PostgreSQL",
	"postgresql": "PostgreSQL",
	"preact": "Preact",
	"PREACT": "Preact",
	"prisma": "Prisma",
	"PRISMA": "Prisma",
	"prometheus": "Prometheus",
	"PROMETHEUS": "Prometheus",
	"PSQL": "PostgreSQL",
	"pulumi": "Pulumi",
	"PULUMI": "Pulumi",
	"puppet": "Puppet",
	"PUPPET": "Puppet",
	"puppeteer": "Puppeteer",
	"PUPPETEER": "Puppeteer",
	"py": "Python",
	"python": "Python",
	"PYTHON": "Python",
	"python2": "Python",
	"python3": "Python",
	"qwik": "Qwik",
	"QWIK": "Qwik",
	"r": "R",
	"R": "R",
	"rabbitmq": "RabbitMQ",
	"RABBITMQ": "RabbitMQ",
	"rails": "Ruby on Rails",
	"REACT": "React",
	"react-i18next": "react-i18next",
	"react-js": "React",
	"react-native": "React Native",
	"react-query": "React Query",
	"react_js": "React",
	"reacti18next": "react-i18next",
	"REACTI18NEXT": "react-i18next",
	"reactjs": "React",
	"ReactJS": "React",
	"reactnative": "React Native",
	"REACTNATIVE": "React Native",
	"reactquery": "React Query",
	"REACTQUERY": "React Query",
	"recoil": "Recoil",
	"RECOIL": "Recoil",
	"redis": "Redis",
	"REDIS": "Redis",
	"redis-pub-sub": "Redis Pub/Sub",
	"redispubsub": "Redis Pub/Sub",
	"REDISPUBSUB": "Redis Pub/Sub",
	"redux": "Redux",
	"REDUX": "Redux",
	"remix": "Remix",
	"REMIX": "Remix",
	"rest": "REST API",
	"rest-api": "REST API",
	"restapi": "REST API",
	"RESTAPI": "REST API",
	"rollup": "Rollup",
	"ROLLUP": "Rollup",
	"ror": "Ruby on Rails",
	"ruby": "Ruby",
	"RUBY": "Ruby",
	"rubyonrails": "Ruby on Rails",
	"RUBYONRAILS": "Ruby on Rails",
	"rust": "Rust",
	"RUST": "Rust",
	"sass": "SASS",
	"SASS": "SASS",
	"scala": "Scala",
	"SCALA": "Scala",
	"scss": "SCSS",
	"SCSS": "SCSS",
	"selenium": "Selenium",
	"SELENIUM": "Selenium",
	"sentry": "Sentry",
	"SENTRY": "Sentry",
	"sequelize": "Sequelize",
	"SEQUELIZE": "Sequelize",
	"snowflake": "Snowflake",
	"SNOWFLAKE": "Snowflake",
	"soap": "SOAP",
	"SOAP": "SOAP",
	"socket-io": "Socket.io",
	"socket.io": "Socket.io",
	"socketio": "Socket.io",
	"SOCKETIO": "Socket.io",
	"solid-js": "SolidJS",
	"solidjs": "SolidJS",
	"SolidJS": "SolidJS",
	"spring": "Spring Framework",
	"spring-boot": "Spring Boot",
	"springboot": "Spring Boot",
	"SPRINGBOOT": "Spring Boot",
	"springframework": "Spring Framework",
	"SpringFramework": "Spring Framework",
	"sqlite": "SQLite",
	"SQLITE": "SQLite",
	"sql server": "Microsoft SQL Server",
	"SQLServer": "Microsoft SQL Server",
	"sqlserver": "Microsoft SQL Server",
	"storybook": "Storybook",
	"STORYBOOK": "Storybook",
	"styled-components": "Styled Components",
	"styledcomponents": "Styled Components",
	"STYLEDCOMPONENTS": "Styled Components",
	"svelte": "Svelte",
	"SVELTE": "Svelte",
	"swc": "SWC",
	"SWC": "SWC",
	"swift": "Swift",
	"SWIFT": "Swift",
	"swr": "SWR",
	"SWR": "SWR",
	"tailwind": "Tailwind CSS",
	"tailwindcss": "Tailwind CSS",
	"TAILWINDCSS": "Tailwind CSS",
	"tanstack-query": "TanStack Query",
	"tanstackquery": "TanStack Query",
	"TANSTACKQUERY": "TanStack Query",
	"terraform": "Terraform",
	"TERRAFORM": "Terraform",
	"testing-library": "Testing Library",
	"testinglibrary": "Testing Library",
	"TESTINGLIBRARY": "Testing Library",
	"three": "Three.js",
	"three.js": "Three.js",
	"threejs": "Three.js",
	"THREEJS": "Three.js",
	"timescale": "TimescaleDB",
	"timescaledb": "TimescaleDB",
	"TIMESCALEDB": "TimescaleDB",
	"travis-ci": "Travis CI",
	"travisci": "Travis CI",
	"TRAVISCI": "Travis CI",
	"ts": "TypeScript",
	"TS": "TypeScript",
	"type-orm": "TypeORM",
	"typeorm": "TypeORM",
	"TYPEORM": "TypeORM",
	"typescript": "TypeScript",
	"uno": "UnoCSS",
	"unocss": "UnoCSS",
	"UNOCSS": "UnoCSS",
	"valtio": "Valtio",
	"VALTIO": "Valtio",
	"vanilla-extract": "Vanilla Extract",
	"vanillaextract": "Vanilla Extract",
	"VANILLAEXTRACT": "Vanilla Extract",
	"vb": "Visual Basic",
	"VB": "Visual Basic",
	"visualbasic": "Visual Basic",
	"VISUALBASIC": "Visual Basic",
	"vite": "Vite",
	"VITE": "Vite",
	"vitest": "Vitest",
	"VITEST": "Vitest",
	"vue": "Vue.js",
	"vue-js": "Vue.js",
	"vuejs": "Vue.js",
	"VueJS": "Vue.js",
	"VUEJS": "Vue.js",
	"web-socket": "WebSocket",
	"webpack": "Webpack",
	"WEBPACK": "Webpack",
	"webrtc": "WebRTC",
	"WEBRTC": "WebRTC",
	"websocket": "WebSocket",
	"WEBSOCKET": "WebSocket",
	"xamarin": "Xamarin",
	"XAMARIN": "Xamarin",
	"xstate": "XState",
	"XSTATE": "XState",
	"yup": "Yup",
	"YUP": "Yup",
	"zod": "Zod",
	"ZOD": "Zod",
	"zustand": "Zustand",
	"ZUSTAND": "Zustand",
} as const;

const normalizeWorkspaceTags = (
	originalTags: string[] = [],
): NormalizeResult => {
	const validTags: string[] = [];
	const droppedTags: string[] = [];

	for (const tag of originalTags) {
		const normalizedTagName = tag.trim().toLowerCase();

		if (Object.hasOwn(VARIANT_TO_CANONICAL, normalizedTagName)) {
			validTags.push(VARIANT_TO_CANONICAL[normalizedTagName] as string);
		} else {
			droppedTags.push(tag);
		}
	}

	return {
		droppedTags,
		normalizedTags: [...new Set(validTags)],
	};
};

async function down(): Promise<void> {}

async function processBatch(
	knex: Knex,
	afterId: number,
): Promise<null | number> {
	const workspaces: WorkspaceRow[] = await knex(TABLE_NAME)
		.select<WorkspaceRow[]>(ColumnName.ID, ColumnName.STACK_TAGS)
		.where(ColumnName.ID, ">", afterId)
		.orderBy(ColumnName.ID, "asc")
		.limit(BATCH_SIZE);

	if (workspaces.length === NO_ROWS) {
		return null;
	}

	const lastRow = workspaces.at(LAST_INDEX);
	const lastId = lastRow ? lastRow[ColumnName.ID] : afterId;

	await knex.transaction(async (trx) => {
		for (const workspace of workspaces) {
			const originalTags = workspace[ColumnName.STACK_TAGS];

			if (!Array.isArray(originalTags)) {
				continue;
			}

			const { droppedTags, normalizedTags } =
				normalizeWorkspaceTags(originalTags);

			const isChanged =
				JSON.stringify(originalTags) !== JSON.stringify(normalizedTags);

			if (!isChanged) {
				continue;
			}

			await trx(TABLE_NAME)
				.where(ColumnName.ID, workspace[ColumnName.ID])
				.update({
					[ColumnName.DROPPED_STACK_TAGS]:
						droppedTags.length > NO_DROPPED_TAGS ? droppedTags : null,
					[ColumnName.STACK_TAGS]: normalizedTags,
					[ColumnName.UPDATED_AT]: trx.fn.now(),
				});
		}
	});

	return lastId;
}

async function up(knex: Knex): Promise<void> {
	let afterId = FIRST_ID;

	for (;;) {
		const lastId = await processBatch(knex, afterId);

		if (lastId === null) {
			break;
		}

		afterId = lastId;
	}
}

export { down, up };
