export {
	type PromptCreateRequestDto,
	type PromptDto,
	type PromptGetAllResponseDto,
	type PromptGetQueryDto,
	type PromptGetRecentResponseDto,
	type PromptItemResponseDto,
	type PromptRecentDto,
	type PromptStreakDayDto,
	type PromptStreakQueryDto,
	type PromptStreakResponseDto,
	type PromptUpdateBodyRequestDto,
	type PromptUpdateIntentRequestDto,
	type PromptUpdateScoreRequestDto,
	type PromptWorkspaceQueryDto,
} from "@promptomat/shared";
