import { TechStackTechDictionary } from "./tech-stack-dictionary.enum.js";

const TechStackVariants = {
	[TechStackTechDictionary.ADONIS_JS]: ["adonisjs", "adonis", "ADONISJS"],
	[TechStackTechDictionary.ALPINE_JS]: [
		"alpinejs",
		"alpine",
		"ALPINEJS",
		"alpine.js",
	],
	[TechStackTechDictionary.AMQP]: ["amqp", "AMQP"],
	[TechStackTechDictionary.ANDROID]: ["android", "ANDROID"],
	[TechStackTechDictionary.ANGULAR]: [
		"angular",
		"AngularJS",
		"angularjs",
		"ng",
		"ANGULAR",
	],
	[TechStackTechDictionary.ANSIBLE]: ["ansible", "ANSIBLE"],
	[TechStackTechDictionary.ARGO_CD]: ["argocd", "argo", "ARGOCD"],
	[TechStackTechDictionary.ASP_NET_CORE]: [
		"aspnetcore",
		"asp.net core",
		"dotnet core",
		"ASPNETCORE",
		"asp.net",
	],
	[TechStackTechDictionary.ASTRO]: ["astro", "ASTRO"],
	[TechStackTechDictionary.AWS]: ["aws", "AWS", "amazon web services"],
	[TechStackTechDictionary.AXIOS]: ["axios", "AXIOS"],
	[TechStackTechDictionary.AZURE]: ["azure", "AZURE", "microsoft azure"],
	[TechStackTechDictionary.BABEL]: ["babel", "BABEL"],
	[TechStackTechDictionary.BUN]: ["bun", "BUN"],
	[TechStackTechDictionary.CAPACITOR]: ["capacitor", "CAPACITOR"],
	[TechStackTechDictionary.CASSANDRA]: ["cassandra", "CASSANDRA"],
	[TechStackTechDictionary.CHAI]: ["chai", "CHAI"],
	[TechStackTechDictionary.CHART_JS]: [
		"chartjs",
		"chart",
		"CHARTJS",
		"chart.js",
	],
	[TechStackTechDictionary.CHEF]: ["chef", "CHEF"],
	[TechStackTechDictionary.CIRCLE_CI]: ["circleci", "circle", "CIRCLECI"],
	[TechStackTechDictionary.CLICK_HOUSE]: ["clickhouse", "click", "CLICKHOUSE"],
	[TechStackTechDictionary.CLOJURE]: ["clojure", "CLOJURE"],
	[TechStackTechDictionary.CORDOVA]: ["cordova", "CORDOVA"],
	[TechStackTechDictionary.CPP]: ["cpp", "c++", "cplusplus", "CPP"],
	[TechStackTechDictionary.CSHARP]: ["csharp", "c#", "CS", "c-sharp"],
	[TechStackTechDictionary.CSS_MODULES]: [
		"cssmodules",
		"css-modules",
		"CSSMODULES",
	],
	[TechStackTechDictionary.CYPRESS]: ["cypress", "CYPRESS"],
	[TechStackTechDictionary.D3_JS]: ["d3js", "d3", "D3JS", "d3.js"],
	[TechStackTechDictionary.DATADOG]: ["datadog", "DATADOG"],
	[TechStackTechDictionary.DATE_FNS]: ["datefns", "date-fns", "DATEFNS"],
	[TechStackTechDictionary.DENO]: ["deno", "DENO"],
	[TechStackTechDictionary.DJANGO]: ["django", "DJANGO"],
	[TechStackTechDictionary.DOCKER]: ["docker", "DOCKER", "docker container"],
	[TechStackTechDictionary.DRIZZLE]: ["drizzle", "DRIZZLE"],
	[TechStackTechDictionary.DYNAMODB]: ["dynamodb", "dynamo", "DYNAMODB"],

	[TechStackTechDictionary.EFFECTOR]: ["effector", "EFFECTOR"],
	[TechStackTechDictionary.ELASTICSEARCH]: [
		"elasticsearch",
		"elastic",
		"es",
		"ELASTICSEARCH",
	],
	[TechStackTechDictionary.ELIXIR]: ["elixir", "ELIXIR"],
	[TechStackTechDictionary.EMOTION]: ["emotion", "EMOTION"],
	[TechStackTechDictionary.ESBUILD]: ["esbuild", "ESBUILD"],
	[TechStackTechDictionary.EXPRESS_JS]: [
		"expressjs",
		"express",
		"EXPRESSJS",
		"express.js",
	],
	[TechStackTechDictionary.FAST_API]: ["fastapi", "FASTAPI", "fast-api"],
	[TechStackTechDictionary.FASTIFY]: ["fastify", "FASTIFY"],
	[TechStackTechDictionary.FIREBASE_FIRESTORE]: [
		"firebasefirestore",
		"firestore",
		"FIREBASEFIRESTORE",
	],
	[TechStackTechDictionary.FLASK]: ["flask", "FLASK"],
	[TechStackTechDictionary.FLUTTER]: ["flutter", "FLUTTER"],
	[TechStackTechDictionary.FRAMER_MOTION]: [
		"framermotion",
		"framer",
		"FRAMERMOTION",
	],
	[TechStackTechDictionary.GATSBY]: ["gatsby", "GATSBY"],
	[TechStackTechDictionary.GCP]: [
		"gcp",
		"GCP",
		"google cloud",
		"google cloud platform",
	],
	[TechStackTechDictionary.GITHUB_ACTIONS]: [
		"githubactions",
		"gh-actions",
		"GITHUBACTIONS",
	],
	[TechStackTechDictionary.GITLAB_CI]: ["gitlabci", "gitlab-ci", "GITLABCI"],
	[TechStackTechDictionary.GO]: ["go", "golang", "GOLANG"],
	[TechStackTechDictionary.GRAFANA]: ["grafana", "GRAFANA"],
	[TechStackTechDictionary.GRAPHQL]: ["graphql", "GRAPHQL", "graph-ql"],
	[TechStackTechDictionary.GRPC]: ["grpc", "GRPC"],
	[TechStackTechDictionary.GSAP]: ["gsap", "GSAP"],
	[TechStackTechDictionary.HASKELL]: ["haskell", "HASKELL"],
	[TechStackTechDictionary.HELM]: ["helm", "HELM"],
	[TechStackTechDictionary.HTML]: ["html", "HTML"],
	[TechStackTechDictionary.HTMX]: ["htmx", "HTMX"],
	[TechStackTechDictionary.I18NEXT]: ["i18next", "I18NEXT"],
	[TechStackTechDictionary.INFLUX_DB]: ["influxdb", "influx", "INFLUXDB"],
	[TechStackTechDictionary.IONIC]: ["ionic", "IONIC"],
	[TechStackTechDictionary.IOS]: ["ios", "IOS"],
	[TechStackTechDictionary.ISTIO]: ["istio", "ISTIO"],
	[TechStackTechDictionary.JAEGER]: ["jaeger", "JAEGER"],
	[TechStackTechDictionary.JASMINE]: ["jasmine", "JASMINE"],
	[TechStackTechDictionary.JAVA]: ["java", "JAVA", "java8", "java11", "java17"],
	[TechStackTechDictionary.JAVASCRIPT]: [
		"javascript",
		"js",
		"JS",
		"javascripts",
	],
	[TechStackTechDictionary.JENKINS]: ["jenkins", "JENKINS"],
	[TechStackTechDictionary.JEST]: ["jest", "JEST"],
	[TechStackTechDictionary.JOI]: ["joi", "JOI"],
	[TechStackTechDictionary.JOTAI]: ["jotai", "JOTAI"],
	[TechStackTechDictionary.KAFKA]: ["kafka", "KAFKA"],
	[TechStackTechDictionary.KARMA]: ["karma", "KARMA"],
	[TechStackTechDictionary.KNEX]: ["knex", "KNEX"],
	[TechStackTechDictionary.KOA]: ["koa", "KOA"],
	[TechStackTechDictionary.KOTLIN]: ["kotlin", "KOTLIN"],
	[TechStackTechDictionary.KUBERNETES]: ["kubernetes", "k8s", "K8S"],
	[TechStackTechDictionary.KYSELY]: ["kysely", "KYSELY"],
	[TechStackTechDictionary.LARAVEL]: ["laravel", "LARAVEL"],
	[TechStackTechDictionary.LEAFLET]: ["leaflet", "LEAFLET"],
	[TechStackTechDictionary.LESS]: ["less", "LESS"],
	[TechStackTechDictionary.LINKERD]: ["linkerd", "LINKERD"],
	[TechStackTechDictionary.LIT]: ["lit", "LIT"],
	[TechStackTechDictionary.LUXON]: ["luxon", "LUXON"],
	[TechStackTechDictionary.MAPBOX]: ["mapbox", "MAPBOX"],
	[TechStackTechDictionary.MARIA_DB]: ["mariadb", "maria", "MARIADB"],
	[TechStackTechDictionary.MATLAB]: ["matlab", "MATLAB"],
	[TechStackTechDictionary.MICROSOFT_SQL_SERVER]: [
		"mssql",
		"sql server",
		"SQLServer",
		"sqlserver",
		"MICROSOFTSQLSERVER",
	],
	[TechStackTechDictionary.MOBX]: ["mobx", "MOBX"],
	[TechStackTechDictionary.MOCHA]: ["mocha", "MOCHA"],
	[TechStackTechDictionary.MONGODB]: ["mongodb", "mongo", "MONGODB"],
	[TechStackTechDictionary.MONGOOSE]: ["mongoose", "MONGOOSE"],
	[TechStackTechDictionary.MQTT]: ["mqtt", "MQTT"],
	[TechStackTechDictionary.MYSQL]: ["mysql", "MYSQL"],
	[TechStackTechDictionary.NEO4J]: ["neo4j", "neo4", "NEO4J"],
	[TechStackTechDictionary.NEST_JS]: [
		"nestjs",
		"NestJS",
		"nest-js",
		"NESTJS",
		"nest",
	],
	[TechStackTechDictionary.NEW_RELIC]: ["newrelic", "new-relic", "NEWRELIC"],
	[TechStackTechDictionary.NEXT_JS]: [
		"nextjs",
		"NextJS",
		"next-js",
		"next_js",
		"NEXTJS",
		"next",
	],
	[TechStackTechDictionary.NODE_JS]: [
		"nodejs",
		"NodeJS",
		"node-js",
		"NODEJS",
		"node",
	],
	[TechStackTechDictionary.NUMPY]: ["numpy", "NUMPY", "np"],
	[TechStackTechDictionary.NUXT_JS]: [
		"nuxtjs",
		"NuxtJS",
		"nuxt-js",
		"NUXTJS",
		"nuxt",
	],
	[TechStackTechDictionary.OPENTELEMETRY]: ["opentelemetry", "otel", "OTEL"],
	[TechStackTechDictionary.PANDA_CSS]: ["pandacss", "panda", "PANDACSS"],
	[TechStackTechDictionary.PARCEL]: ["parcel", "PARCEL"],
	[TechStackTechDictionary.PHP]: ["php", "PHP", "php7", "php8"],
	[TechStackTechDictionary.PLAYWRIGHT]: ["playwright", "PLAYWRIGHT"],
	[TechStackTechDictionary.POSTGRESQL]: [
		"postgresql",
		"postgres",
		"Postgres",
		"PSQL",
		"pg",
	],
	[TechStackTechDictionary.PREACT]: ["preact", "PREACT"],
	[TechStackTechDictionary.PRISMA]: ["prisma", "PRISMA"],
	[TechStackTechDictionary.PROMETHEUS]: ["prometheus", "PROMETHEUS"],
	[TechStackTechDictionary.PULUMI]: ["pulumi", "PULUMI"],
	[TechStackTechDictionary.PUPPET]: ["puppet", "PUPPET"],
	[TechStackTechDictionary.PUPPETEER]: ["puppeteer", "PUPPETEER"],
	[TechStackTechDictionary.PYTHON]: [
		"python",
		"py",
		"PYTHON",
		"python3",
		"python2",
	],
	[TechStackTechDictionary.QWIK]: ["qwik", "QWIK"],
	[TechStackTechDictionary.R]: ["r", "R"],
	[TechStackTechDictionary.RABBITMQ]: ["rabbitmq", "RABBITMQ"],
	[TechStackTechDictionary.REACT]: [
		"reactjs",
		"ReactJS",
		"react-js",
		"react_js",
		"REACT",
	],
	[TechStackTechDictionary.REACT_I18NEXT]: [
		"reacti18next",
		"react-i18next",
		"REACTI18NEXT",
	],
	[TechStackTechDictionary.REACT_NATIVE]: [
		"reactnative",
		"react-native",
		"REACTNATIVE",
	],
	[TechStackTechDictionary.REACT_QUERY]: [
		"reactquery",
		"react-query",
		"REACTQUERY",
	],
	[TechStackTechDictionary.RECOIL]: ["recoil", "RECOIL"],
	[TechStackTechDictionary.REDIS]: ["redis", "REDIS"],
	[TechStackTechDictionary.REDIS_PUB_SUB]: [
		"redispubsub",
		"redis-pub-sub",
		"REDISPUBSUB",
	],
	[TechStackTechDictionary.REDUX]: ["redux", "REDUX"],
	[TechStackTechDictionary.REMIX]: ["remix", "REMIX"],
	[TechStackTechDictionary.REST_API]: [
		"restapi",
		"rest-api",
		"rest",
		"RESTAPI",
	],
	[TechStackTechDictionary.ROLLUP]: ["rollup", "ROLLUP"],
	[TechStackTechDictionary.RUBY]: ["ruby", "RUBY"],
	[TechStackTechDictionary.RUBY_ON_RAILS]: [
		"rubyonrails",
		"rails",
		"ror",
		"RUBYONRAILS",
	],
	[TechStackTechDictionary.RUST]: ["rust", "RUST"],
	[TechStackTechDictionary.SASS]: ["sass", "SASS"],
	[TechStackTechDictionary.SCALA]: ["scala", "SCALA"],
	[TechStackTechDictionary.SCSS]: ["scss", "SCSS"],
	[TechStackTechDictionary.SELENIUM]: ["selenium", "SELENIUM"],
	[TechStackTechDictionary.SENTRY]: ["sentry", "SENTRY"],
	[TechStackTechDictionary.SEQUELIZE]: ["sequelize", "SEQUELIZE"],
	[TechStackTechDictionary.SNOWFLAKE]: ["snowflake", "SNOWFLAKE"],
	[TechStackTechDictionary.SOAP]: ["soap", "SOAP"],
	[TechStackTechDictionary.SOCKET_IO]: [
		"socketio",
		"socket-io",
		"SOCKETIO",
		"socket.io",
	],
	[TechStackTechDictionary.SOLID_JS]: ["solidjs", "SolidJS", "solid-js"],
	[TechStackTechDictionary.SPRING_BOOT]: [
		"springboot",
		"spring-boot",
		"SPRINGBOOT",
	],
	[TechStackTechDictionary.SPRING_FRAMEWORK]: [
		"springframework",
		"spring",
		"SpringFramework",
	],
	[TechStackTechDictionary.SQLITE]: ["sqlite", "SQLITE"],
	[TechStackTechDictionary.STORYBOOK]: ["storybook", "STORYBOOK"],
	[TechStackTechDictionary.STYLED_COMPONENTS]: [
		"styledcomponents",
		"styled-components",
		"STYLEDCOMPONENTS",
	],
	[TechStackTechDictionary.SVELTE]: ["svelte", "SVELTE"],
	[TechStackTechDictionary.SWC]: ["swc", "SWC"],
	[TechStackTechDictionary.SWIFT]: ["swift", "SWIFT"],
	[TechStackTechDictionary.SWR]: ["swr", "SWR"],
	[TechStackTechDictionary.TAILWIND_CSS]: [
		"tailwindcss",
		"tailwind",
		"TAILWINDCSS",
	],
	[TechStackTechDictionary.TANSTACK_QUERY]: [
		"tanstackquery",
		"tanstack-query",
		"TANSTACKQUERY",
	],
	[TechStackTechDictionary.TERRAFORM]: ["terraform", "TERRAFORM"],
	[TechStackTechDictionary.TESTING_LIBRARY]: [
		"testinglibrary",
		"testing-library",
		"TESTINGLIBRARY",
	],
	[TechStackTechDictionary.THREE_JS]: [
		"threejs",
		"three",
		"THREEJS",
		"three.js",
	],
	[TechStackTechDictionary.TIMESCALE_DB]: [
		"timescaledb",
		"timescale",
		"TIMESCALEDB",
	],
	[TechStackTechDictionary.TRAVIS_CI]: ["travisci", "travis-ci", "TRAVISCI"],
	[TechStackTechDictionary.TYPE_ORM]: ["typeorm", "type-orm", "TYPEORM"],
	[TechStackTechDictionary.TYPESCRIPT]: ["typescript", "ts", "TS"],
	[TechStackTechDictionary.UNO_CSS]: ["unocss", "uno", "UNOCSS"],
	[TechStackTechDictionary.VALTIO]: ["valtio", "VALTIO"],
	[TechStackTechDictionary.VANILLA_EXTRACT]: [
		"vanillaextract",
		"vanilla-extract",
		"VANILLAEXTRACT",
	],
	[TechStackTechDictionary.VISUAL_BASIC]: [
		"visualbasic",
		"vb",
		"VB",
		"VISUALBASIC",
	],
	[TechStackTechDictionary.VITE]: ["vite", "VITE"],
	[TechStackTechDictionary.VITEST]: ["vitest", "VITEST"],
	[TechStackTechDictionary.VUE]: ["vuejs", "VueJS", "vue-js", "VUEJS", "vue"],
	[TechStackTechDictionary.WEB_RTC]: ["webrtc", "WEBRTC"],
	[TechStackTechDictionary.WEB_SOCKET]: [
		"websocket",
		"web-socket",
		"WEBSOCKET",
	],
	[TechStackTechDictionary.WEBPACK]: ["webpack", "WEBPACK"],
	[TechStackTechDictionary.XAMARIN]: ["xamarin", "XAMARIN"],
	[TechStackTechDictionary.XSTATE]: ["xstate", "XSTATE"],
	[TechStackTechDictionary.YUP]: ["yup", "YUP"],
	[TechStackTechDictionary.ZOD]: ["zod", "ZOD"],
	[TechStackTechDictionary.ZUSTAND]: ["zustand", "ZUSTAND"],
} as const;

export { TechStackVariants };
