import { TECH_STACK_DICTIONARY } from "./dictionary.enum.js";

const TECH_STACK_VARIANTS = {
	[TECH_STACK_DICTIONARY.ADONIS_JS]: ["adonisjs", "adonis", "ADONISJS"],
	[TECH_STACK_DICTIONARY.ALPINE_JS]: [
		"alpinejs",
		"alpine",
		"ALPINEJS",
		"alpine.js",
	],
	[TECH_STACK_DICTIONARY.AMQP]: ["amqp", "AMQP"],
	[TECH_STACK_DICTIONARY.ANDROID]: ["android", "ANDROID"],
	[TECH_STACK_DICTIONARY.ANGULAR]: [
		"angular",
		"AngularJS",
		"angularjs",
		"ng",
		"ANGULAR",
	],
	[TECH_STACK_DICTIONARY.ANSIBLE]: ["ansible", "ANSIBLE"],
	[TECH_STACK_DICTIONARY.ARGO_CD]: ["argocd", "argo", "ARGOCD"],
	[TECH_STACK_DICTIONARY.ASP_NET_CORE]: [
		"aspnetcore",
		"asp.net core",
		"dotnet core",
		"ASPNETCORE",
		"asp.net",
	],
	[TECH_STACK_DICTIONARY.ASTRO]: ["astro", "ASTRO"],
	[TECH_STACK_DICTIONARY.AWS]: ["aws", "AWS", "amazon web services"],
	[TECH_STACK_DICTIONARY.AXIOS]: ["axios", "AXIOS"],
	[TECH_STACK_DICTIONARY.AZURE]: ["azure", "AZURE", "microsoft azure"],
	[TECH_STACK_DICTIONARY.BABEL]: ["babel", "BABEL"],
	[TECH_STACK_DICTIONARY.BUN]: ["bun", "BUN"],
	[TECH_STACK_DICTIONARY.CAPACITOR]: ["capacitor", "CAPACITOR"],
	[TECH_STACK_DICTIONARY.CASSANDRA]: ["cassandra", "CASSANDRA"],
	[TECH_STACK_DICTIONARY.CHAI]: ["chai", "CHAI"],
	[TECH_STACK_DICTIONARY.CHART_JS]: ["chartjs", "chart", "CHARTJS", "chart.js"],
	[TECH_STACK_DICTIONARY.CHEF]: ["chef", "CHEF"],
	[TECH_STACK_DICTIONARY.CIRCLE_CI]: ["circleci", "circle", "CIRCLECI"],
	[TECH_STACK_DICTIONARY.CLICK_HOUSE]: ["clickhouse", "click", "CLICKHOUSE"],
	[TECH_STACK_DICTIONARY.CLOJURE]: ["clojure", "CLOJURE"],
	[TECH_STACK_DICTIONARY.CORDOVA]: ["cordova", "CORDOVA"],
	[TECH_STACK_DICTIONARY.CPP]: ["cpp", "c++", "cplusplus", "CPP"],
	[TECH_STACK_DICTIONARY.CSHARP]: ["csharp", "c#", "CS", "c-sharp"],
	[TECH_STACK_DICTIONARY.CSS_MODULES]: [
		"cssmodules",
		"css-modules",
		"CSSMODULES",
	],
	[TECH_STACK_DICTIONARY.CYPRESS]: ["cypress", "CYPRESS"],
	[TECH_STACK_DICTIONARY.D3_JS]: ["d3js", "d3", "D3JS", "d3.js"],
	[TECH_STACK_DICTIONARY.DATADOG]: ["datadog", "DATADOG"],
	[TECH_STACK_DICTIONARY.DATE_FNS]: ["datefns", "date-fns", "DATEFNS"],
	[TECH_STACK_DICTIONARY.DENO]: ["deno", "DENO"],
	[TECH_STACK_DICTIONARY.DJANGO]: ["django", "DJANGO"],
	[TECH_STACK_DICTIONARY.DOCKER]: ["docker", "DOCKER", "docker container"],
	[TECH_STACK_DICTIONARY.DRIZZLE]: ["drizzle", "DRIZZLE"],
	[TECH_STACK_DICTIONARY.DYNAMODB]: ["dynamodb", "dynamo", "DYNAMODB"],

	[TECH_STACK_DICTIONARY.EFFECTOR]: ["effector", "EFFECTOR"],
	[TECH_STACK_DICTIONARY.ELASTICSEARCH]: [
		"elasticsearch",
		"elastic",
		"es",
		"ELASTICSEARCH",
	],
	[TECH_STACK_DICTIONARY.ELIXIR]: ["elixir", "ELIXIR"],
	[TECH_STACK_DICTIONARY.EMOTION]: ["emotion", "EMOTION"],
	[TECH_STACK_DICTIONARY.ESBUILD]: ["esbuild", "ESBUILD"],
	[TECH_STACK_DICTIONARY.EXPRESS_JS]: [
		"expressjs",
		"express",
		"EXPRESSJS",
		"express.js",
	],
	[TECH_STACK_DICTIONARY.FAST_API]: ["fastapi", "FASTAPI", "fast-api"],
	[TECH_STACK_DICTIONARY.FASTIFY]: ["fastify", "FASTIFY"],
	[TECH_STACK_DICTIONARY.FIREBASE_FIRESTORE]: [
		"firebasefirestore",
		"firestore",
		"FIREBASEFIRESTORE",
	],
	[TECH_STACK_DICTIONARY.FLASK]: ["flask", "FLASK"],
	[TECH_STACK_DICTIONARY.FLUTTER]: ["flutter", "FLUTTER"],
	[TECH_STACK_DICTIONARY.FRAMER_MOTION]: [
		"framermotion",
		"framer",
		"FRAMERMOTION",
	],
	[TECH_STACK_DICTIONARY.GATSBY]: ["gatsby", "GATSBY"],
	[TECH_STACK_DICTIONARY.GCP]: [
		"gcp",
		"GCP",
		"google cloud",
		"google cloud platform",
	],
	[TECH_STACK_DICTIONARY.GITHUB_ACTIONS]: [
		"githubactions",
		"gh-actions",
		"GITHUBACTIONS",
	],
	[TECH_STACK_DICTIONARY.GITLAB_CI]: ["gitlabci", "gitlab-ci", "GITLABCI"],
	[TECH_STACK_DICTIONARY.GO]: ["go", "golang", "GOLANG"],
	[TECH_STACK_DICTIONARY.GRAFANA]: ["grafana", "GRAFANA"],
	[TECH_STACK_DICTIONARY.GRAPHQL]: ["graphql", "GRAPHQL", "graph-ql"],
	[TECH_STACK_DICTIONARY.GRPC]: ["grpc", "GRPC"],
	[TECH_STACK_DICTIONARY.GSAP]: ["gsap", "GSAP"],
	[TECH_STACK_DICTIONARY.HASKELL]: ["haskell", "HASKELL"],
	[TECH_STACK_DICTIONARY.HELM]: ["helm", "HELM"],
	[TECH_STACK_DICTIONARY.HTML]: ["html", "HTML"],
	[TECH_STACK_DICTIONARY.HTMX]: ["htmx", "HTMX"],
	[TECH_STACK_DICTIONARY.I18NEXT]: ["i18next", "I18NEXT"],
	[TECH_STACK_DICTIONARY.INFLUX_DB]: ["influxdb", "influx", "INFLUXDB"],
	[TECH_STACK_DICTIONARY.IONIC]: ["ionic", "IONIC"],
	[TECH_STACK_DICTIONARY.IOS]: ["ios", "IOS"],
	[TECH_STACK_DICTIONARY.ISTIO]: ["istio", "ISTIO"],
	[TECH_STACK_DICTIONARY.JAEGER]: ["jaeger", "JAEGER"],
	[TECH_STACK_DICTIONARY.JASMINE]: ["jasmine", "JASMINE"],
	[TECH_STACK_DICTIONARY.JAVA]: ["java", "JAVA", "java8", "java11", "java17"],
	[TECH_STACK_DICTIONARY.JAVASCRIPT]: ["javascript", "js", "JS", "javascripts"],
	[TECH_STACK_DICTIONARY.JENKINS]: ["jenkins", "JENKINS"],
	[TECH_STACK_DICTIONARY.JEST]: ["jest", "JEST"],
	[TECH_STACK_DICTIONARY.JOI]: ["joi", "JOI"],
	[TECH_STACK_DICTIONARY.JOTAI]: ["jotai", "JOTAI"],
	[TECH_STACK_DICTIONARY.KAFKA]: ["kafka", "KAFKA"],
	[TECH_STACK_DICTIONARY.KARMA]: ["karma", "KARMA"],
	[TECH_STACK_DICTIONARY.KNEX]: ["knex", "KNEX"],
	[TECH_STACK_DICTIONARY.KOA]: ["koa", "KOA"],
	[TECH_STACK_DICTIONARY.KOTLIN]: ["kotlin", "KOTLIN"],
	[TECH_STACK_DICTIONARY.KUBERNETES]: ["kubernetes", "k8s", "K8S"],
	[TECH_STACK_DICTIONARY.KYSELY]: ["kysely", "KYSELY"],
	[TECH_STACK_DICTIONARY.LARAVEL]: ["laravel", "LARAVEL"],
	[TECH_STACK_DICTIONARY.LEAFLET]: ["leaflet", "LEAFLET"],
	[TECH_STACK_DICTIONARY.LESS]: ["less", "LESS"],
	[TECH_STACK_DICTIONARY.LINKERD]: ["linkerd", "LINKERD"],
	[TECH_STACK_DICTIONARY.LIT]: ["lit", "LIT"],
	[TECH_STACK_DICTIONARY.LUXON]: ["luxon", "LUXON"],
	[TECH_STACK_DICTIONARY.MAPBOX]: ["mapbox", "MAPBOX"],
	[TECH_STACK_DICTIONARY.MARIA_DB]: ["mariadb", "maria", "MARIADB"],
	[TECH_STACK_DICTIONARY.MATLAB]: ["matlab", "MATLAB"],
	[TECH_STACK_DICTIONARY.MICROSOFT_SQL_SERVER]: [
		"mssql",
		"sql server",
		"SQLServer",
		"sqlserver",
		"MICROSOFTSQLSERVER",
	],
	[TECH_STACK_DICTIONARY.MOBX]: ["mobx", "MOBX"],
	[TECH_STACK_DICTIONARY.MOCHA]: ["mocha", "MOCHA"],
	[TECH_STACK_DICTIONARY.MONGODB]: ["mongodb", "mongo", "MONGODB"],
	[TECH_STACK_DICTIONARY.MONGOOSE]: ["mongoose", "MONGOOSE"],
	[TECH_STACK_DICTIONARY.MQTT]: ["mqtt", "MQTT"],
	[TECH_STACK_DICTIONARY.MYSQL]: ["mysql", "MYSQL"],
	[TECH_STACK_DICTIONARY.NEO4J]: ["neo4j", "neo4", "NEO4J"],
	[TECH_STACK_DICTIONARY.NEST_JS]: [
		"nestjs",
		"NestJS",
		"nest-js",
		"NESTJS",
		"nest",
	],
	[TECH_STACK_DICTIONARY.NEW_RELIC]: ["newrelic", "new-relic", "NEWRELIC"],
	[TECH_STACK_DICTIONARY.NEXT_JS]: [
		"nextjs",
		"NextJS",
		"next-js",
		"next_js",
		"NEXTJS",
		"next",
	],
	[TECH_STACK_DICTIONARY.NODE_JS]: [
		"nodejs",
		"NodeJS",
		"node-js",
		"NODEJS",
		"node",
	],
	[TECH_STACK_DICTIONARY.NUMPY]: ["numpy", "NUMPY", "np"],
	[TECH_STACK_DICTIONARY.NUXT_JS]: [
		"nuxtjs",
		"NuxtJS",
		"nuxt-js",
		"NUXTJS",
		"nuxt",
	],
	[TECH_STACK_DICTIONARY.OPENTELEMETRY]: ["opentelemetry", "otel", "OTEL"],
	[TECH_STACK_DICTIONARY.PANDA_CSS]: ["pandacss", "panda", "PANDACSS"],
	[TECH_STACK_DICTIONARY.PARCEL]: ["parcel", "PARCEL"],
	[TECH_STACK_DICTIONARY.PHP]: ["php", "PHP", "php7", "php8"],
	[TECH_STACK_DICTIONARY.PLAYWRIGHT]: ["playwright", "PLAYWRIGHT"],
	[TECH_STACK_DICTIONARY.POSTGRESQL]: [
		"postgresql",
		"postgres",
		"Postgres",
		"PSQL",
		"pg",
	],
	[TECH_STACK_DICTIONARY.PREACT]: ["preact", "PREACT"],
	[TECH_STACK_DICTIONARY.PRISMA]: ["prisma", "PRISMA"],
	[TECH_STACK_DICTIONARY.PROMETHEUS]: ["prometheus", "PROMETHEUS"],
	[TECH_STACK_DICTIONARY.PULUMI]: ["pulumi", "PULUMI"],
	[TECH_STACK_DICTIONARY.PUPPET]: ["puppet", "PUPPET"],
	[TECH_STACK_DICTIONARY.PUPPETEER]: ["puppeteer", "PUPPETEER"],
	[TECH_STACK_DICTIONARY.PYTHON]: [
		"python",
		"py",
		"PYTHON",
		"python3",
		"python2",
	],
	[TECH_STACK_DICTIONARY.QWIK]: ["qwik", "QWIK"],
	[TECH_STACK_DICTIONARY.R]: ["r", "R"],
	[TECH_STACK_DICTIONARY.RABBITMQ]: ["rabbitmq", "RABBITMQ"],
	[TECH_STACK_DICTIONARY.REACT]: [
		"reactjs",
		"ReactJS",
		"react-js",
		"react_js",
		"REACT",
	],
	[TECH_STACK_DICTIONARY.REACT_I18NEXT]: [
		"reacti18next",
		"react-i18next",
		"REACTI18NEXT",
	],
	[TECH_STACK_DICTIONARY.REACT_NATIVE]: [
		"reactnative",
		"react-native",
		"REACTNATIVE",
	],
	[TECH_STACK_DICTIONARY.REACT_QUERY]: [
		"reactquery",
		"react-query",
		"REACTQUERY",
	],
	[TECH_STACK_DICTIONARY.RECOIL]: ["recoil", "RECOIL"],
	[TECH_STACK_DICTIONARY.REDIS]: ["redis", "REDIS"],
	[TECH_STACK_DICTIONARY.REDIS_PUB_SUB]: [
		"redispubsub",
		"redis-pub-sub",
		"REDISPUBSUB",
	],
	[TECH_STACK_DICTIONARY.REDUX]: ["redux", "REDUX"],
	[TECH_STACK_DICTIONARY.REMIX]: ["remix", "REMIX"],
	[TECH_STACK_DICTIONARY.REST_API]: ["restapi", "rest-api", "rest", "RESTAPI"],
	[TECH_STACK_DICTIONARY.ROLLUP]: ["rollup", "ROLLUP"],
	[TECH_STACK_DICTIONARY.RUBY]: ["ruby", "RUBY"],
	[TECH_STACK_DICTIONARY.RUBY_ON_RAILS]: [
		"rubyonrails",
		"rails",
		"ror",
		"RUBYONRAILS",
	],
	[TECH_STACK_DICTIONARY.RUST]: ["rust", "RUST"],
	[TECH_STACK_DICTIONARY.SASS]: ["sass", "SASS"],
	[TECH_STACK_DICTIONARY.SCALA]: ["scala", "SCALA"],
	[TECH_STACK_DICTIONARY.SCSS]: ["scss", "SCSS"],
	[TECH_STACK_DICTIONARY.SELENIUM]: ["selenium", "SELENIUM"],
	[TECH_STACK_DICTIONARY.SENTRY]: ["sentry", "SENTRY"],
	[TECH_STACK_DICTIONARY.SEQUELIZE]: ["sequelize", "SEQUELIZE"],
	[TECH_STACK_DICTIONARY.SNOWFLAKE]: ["snowflake", "SNOWFLAKE"],
	[TECH_STACK_DICTIONARY.SOAP]: ["soap", "SOAP"],
	[TECH_STACK_DICTIONARY.SOCKET_IO]: [
		"socketio",
		"socket-io",
		"SOCKETIO",
		"socket.io",
	],
	[TECH_STACK_DICTIONARY.SOLID_JS]: ["solidjs", "SolidJS", "solid-js"],
	[TECH_STACK_DICTIONARY.SPRING_BOOT]: [
		"springboot",
		"spring-boot",
		"SPRINGBOOT",
	],
	[TECH_STACK_DICTIONARY.SPRING_FRAMEWORK]: [
		"springframework",
		"spring",
		"SpringFramework",
	],
	[TECH_STACK_DICTIONARY.SQLITE]: ["sqlite", "SQLITE"],
	[TECH_STACK_DICTIONARY.STORYBOOK]: ["storybook", "STORYBOOK"],
	[TECH_STACK_DICTIONARY.STYLED_COMPONENTS]: [
		"styledcomponents",
		"styled-components",
		"STYLEDCOMPONENTS",
	],
	[TECH_STACK_DICTIONARY.SVELTE]: ["svelte", "SVELTE"],
	[TECH_STACK_DICTIONARY.SWC]: ["swc", "SWC"],
	[TECH_STACK_DICTIONARY.SWIFT]: ["swift", "SWIFT"],
	[TECH_STACK_DICTIONARY.SWR]: ["swr", "SWR"],
	[TECH_STACK_DICTIONARY.TAILWIND_CSS]: [
		"tailwindcss",
		"tailwind",
		"TAILWINDCSS",
	],
	[TECH_STACK_DICTIONARY.TANSTACK_QUERY]: [
		"tanstackquery",
		"tanstack-query",
		"TANSTACKQUERY",
	],
	[TECH_STACK_DICTIONARY.TERRAFORM]: ["terraform", "TERRAFORM"],
	[TECH_STACK_DICTIONARY.TESTING_LIBRARY]: [
		"testinglibrary",
		"testing-library",
		"TESTINGLIBRARY",
	],
	[TECH_STACK_DICTIONARY.THREE_JS]: ["threejs", "three", "THREEJS", "three.js"],
	[TECH_STACK_DICTIONARY.TIMESCALE_DB]: [
		"timescaledb",
		"timescale",
		"TIMESCALEDB",
	],
	[TECH_STACK_DICTIONARY.TRAVIS_CI]: ["travisci", "travis-ci", "TRAVISCI"],
	[TECH_STACK_DICTIONARY.TYPE_ORM]: ["typeorm", "type-orm", "TYPEORM"],
	[TECH_STACK_DICTIONARY.TYPESCRIPT]: ["typescript", "ts", "TS"],
	[TECH_STACK_DICTIONARY.UNO_CSS]: ["unocss", "uno", "UNOCSS"],
	[TECH_STACK_DICTIONARY.VALTIO]: ["valtio", "VALTIO"],
	[TECH_STACK_DICTIONARY.VANILLA_EXTRACT]: [
		"vanillaextract",
		"vanilla-extract",
		"VANILLAEXTRACT",
	],
	[TECH_STACK_DICTIONARY.VISUAL_BASIC]: [
		"visualbasic",
		"vb",
		"VB",
		"VISUALBASIC",
	],
	[TECH_STACK_DICTIONARY.VITE]: ["vite", "VITE"],
	[TECH_STACK_DICTIONARY.VITEST]: ["vitest", "VITEST"],
	[TECH_STACK_DICTIONARY.VUE]: ["vuejs", "VueJS", "vue-js", "VUEJS", "vue"],
	[TECH_STACK_DICTIONARY.WEB_RTC]: ["webrtc", "WEBRTC"],
	[TECH_STACK_DICTIONARY.WEB_SOCKET]: ["websocket", "web-socket", "WEBSOCKET"],
	[TECH_STACK_DICTIONARY.WEBPACK]: ["webpack", "WEBPACK"],
	[TECH_STACK_DICTIONARY.XAMARIN]: ["xamarin", "XAMARIN"],
	[TECH_STACK_DICTIONARY.XSTATE]: ["xstate", "XSTATE"],
	[TECH_STACK_DICTIONARY.YUP]: ["yup", "YUP"],
	[TECH_STACK_DICTIONARY.ZOD]: ["zod", "ZOD"],
	[TECH_STACK_DICTIONARY.ZUSTAND]: ["zustand", "ZUSTAND"],
} as const;

export { TECH_STACK_VARIANTS };
