const AuthValidationRule = {
	EMAIL_MINIMUM_LENGTH: 1,
	NICKNAME_MAXIMUM_LENGTH: 25,
	NICKNAME_MINIMUM_LENGTH: 3,
	NICKNAME_REGEX: /^\w+$/,
	PASSWORD_MAXIMUM_LENGTH: 64,
	PASSWORD_MINIMUM_LENGTH: 4,
	PASSWORD_SIGN_IN_MINIMUM_LENGTH: 1,
} as const;

export { AuthValidationRule };
