const AuthErrorCode = {
	AUTH_EMAIL_ALREADY_EXISTS: "AUTH_EMAIL_ALREADY_EXISTS",
	AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
	AUTH_NICKNAME_ALREADY_EXISTS: "AUTH_NICKNAME_ALREADY_EXISTS",
	AUTH_RESET_TOKEN_EXPIRED: "AUTH_RESET_TOKEN_EXPIRED",
	AUTH_RESET_TOKEN_INVALID: "AUTH_RESET_TOKEN_INVALID",
	AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
} as const;

export { AuthErrorCode };
