const CURRENT_LOOKBACK_DAYS = 6;
const PREVIOUS_WINDOW_MULTIPLIER = 2;
const PREVIOUS_WINDOW_OFFSET = 1;

const WeeklyChangeWindow = {
	CURRENT_LOOKBACK_DAYS,
	PREVIOUS_LOOKBACK_DAYS:
		CURRENT_LOOKBACK_DAYS * PREVIOUS_WINDOW_MULTIPLIER + PREVIOUS_WINDOW_OFFSET,
} as const;

export { WeeklyChangeWindow };
