const ACCOUNT_MENU_ID = "account-menu";
const NICKNAME_INITIALS_LENGTH = 2;
const PANEL_CLOSE_DURATION_MS = 180;
const REDUCED_MOTION_DURATION_MS = 0;

export {
	ACCOUNT_MENU_ID,
	NICKNAME_INITIALS_LENGTH,
	PANEL_CLOSE_DURATION_MS,
	REDUCED_MOTION_DURATION_MS,
};
