const TextGenerationErrorCode = {
	CONFIG_INVALID: "CONFIG_INVALID",
	OUTPUT_UNUSABLE: "OUTPUT_UNUSABLE",
	UNAVAILABLE: "UNAVAILABLE",
	UNCLASSIFIED: "UNCLASSIFIED",
	VALIDATION_FAILED: "VALIDATION_FAILED",
} as const;

export { TextGenerationErrorCode };
