const MILLISECONDS_PER_SECOND = 1000;

const SECONDS_PER_MINUTE = 60;

const MINUTES_PER_HOUR = 60;

const HOURS_PER_DAY = 24;

const EXPIRING_SOON_DAYS = 7;

const NO_TIME_REMAINING = 0;

const EXPIRING_SOON_MS =
	EXPIRING_SOON_DAYS *
	HOURS_PER_DAY *
	MINUTES_PER_HOUR *
	SECONDS_PER_MINUTE *
	MILLISECONDS_PER_SECOND;

export { EXPIRING_SOON_MS, NO_TIME_REMAINING };
