const TextGenerationErrorCode = {
	MAX_TOKENS_EXCEEDS_THRESHOLD: "MAX_TOKENS_EXCEEDS_THRESHOLD",
	UNABLE_TO_GENERATE_STRUCTURE: "UNABLE_TO_GENERATE_STRUCTURE",
	UNABLE_TO_GENERATE_TEXT: "UNABLE_TO_GENERATE_TEXT",
} as const;

export { TextGenerationErrorCode };
