const TokenErrorMessage = {
	INVALID_TOKEN: "INVALID_TOKEN",
	INVALID_TOKEN_PAYLOAD: "INVALID_TOKEN_PAYLOAD",
	INVALID_TOKEN_SIGNATURE: "INVALID_TOKEN_SIGNATURE",
	TOKEN_HAS_EXPIRED: "TOKEN_HAS_EXPIRED",
} as const;

export { TokenErrorMessage };
