const BLOCKING_IDS_EMPTY_LENGTH = 0;
const LAST_INDEX_FROM_END = -1;
const DEFAULT_NOTIFICATION_DURATION_MS = 30_000;
const DEFAULT_NOTIFICATION_TYPE = "info" as const;

export {
	BLOCKING_IDS_EMPTY_LENGTH,
	DEFAULT_NOTIFICATION_DURATION_MS,
	DEFAULT_NOTIFICATION_TYPE,
	LAST_INDEX_FROM_END,
};
