const LAST_INDEX_FROM_END = -1;
const DEFAULT_NOTIFICATION_DURATION_MS = 6000;
const NOTIFICATION_CLOSING_DURATION_MS = 200;
const DEFAULT_NOTIFICATION_TYPE = "info" as const;

export {
	DEFAULT_NOTIFICATION_DURATION_MS,
	DEFAULT_NOTIFICATION_TYPE,
	LAST_INDEX_FROM_END,
	NOTIFICATION_CLOSING_DURATION_MS,
};
