const RepositoryBindingsErrorCode = {
	NO_REMOTE_CONFIGURED: "NO_REMOTE_CONFIGURED",
	REPOSITORY_BINDING_ALREADY_EXISTS: "REPOSITORY_BINDING_ALREADY_EXISTS",
	UNRECOGNIZED_REPOSITORY_FORMAT: "UNRECOGNIZED_REPOSITORY_FORMAT",
} as const;

export { RepositoryBindingsErrorCode };
