const GenerateLabel = {
	APPLY: "Apply",
	BODY_FIELD: "Prompt body",
	CANCEL: "Cancel",
	COPY_PROMPT: "Copy prompt",
	DESCRIPTION_FIELD: "Task description",
	DESCRIPTION_PLACEHOLDER:
		"Describe your coding task (e.g., Implement middleware session validation)",
	DISCARD: "Discard",
	EDIT: "Edit",
	EDITED_KICKER: "Edited by you",
	FALLBACK_KICKER: "Closest stored prompt",
	GENERATED_KICKER: "Generated",
	OPEN_IN_LOG: "Open in log",
	PAGE_DESCRIPTION:
		"Promptomat assembles it from the highest-scoring prompts in this workspace and shows which ones it used.",
	PAGE_LABEL: "Compose",
	PAGE_TITLE: "Write the task. We'll build the prompt.",
	PROVENANCE_FROM: "From",
	PROVENANCE_IN: "in",
	RATE_HEADING: "Rate this prompt",
	RECOMPOSE: "Recompose",
	RECOMPOSITION_ONE: "recomposition",
	RECOMPOSITIONS_LEFT: "left",
	RECOMPOSITIONS_MANY: "recompositions",
	RECORD_PROMPT_LINK: "Record a prompt",
	RETRY: "Retry",
	STORED_PROMPT_ONE: "stored prompt",
	STORED_PROMPTS_MANY: "stored prompts",
	SUBMIT: "Generate",
	SUBMITTING: "Generating",
	TRY_AGAIN: "Try again",
	WORKSPACE_CAPTION: "Generating in",
	WORKSPACE_FIELD: "Workspace",
	WORKSPACE_PLACEHOLDER: "Select workspace",
} as const;

export { GenerateLabel };
