const ContributorsErrorCode = {
	CONTRIBUTOR_ALREADY_EXISTS: "CONTRIBUTOR_ALREADY_EXISTS",
	CONTRIBUTOR_NOT_FOUND: "CONTRIBUTOR_NOT_FOUND",
	WORKSPACE_OWNER_CANNOT_BE_ADDED_AS_CONTRIBUTOR:
		"WORKSPACE_OWNER_CANNOT_BE_ADDED_AS_CONTRIBUTOR",
} as const;

export { ContributorsErrorCode };
