const WorkspacesErrorCode = {
	LAST_WORKSPACE_DELETION_NOT_ALLOWED: "LAST_WORKSPACE_DELETION_NOT_ALLOWED",
	WORKSPACE_ALREADY_EXISTS: "WORKSPACE_ALREADY_EXISTS",
	WORKSPACE_NOT_FOUND: "WORKSPACE_NOT_FOUND",
} as const;

export { WorkspacesErrorCode };
