const WorkspacesErrorCode = {
	WORKSPACE_ACCESS_DENIED: "WORKSPACE_ACCESS_DENIED",
	WORKSPACE_ACTION_FORBIDDEN: "WORKSPACE_ACTION_FORBIDDEN",
	WORKSPACE_ALREADY_EXISTS: "WORKSPACE_ALREADY_EXISTS",
} as const;

export { WorkspacesErrorCode };
