name: Continuous Integration Pull Request

on:
  pull_request:
    types:
      - assigned
      - unassigned
      - opened
      - edited
      - synchronize
      - reopened
      - labeled
      - unlabeled
      - ready_for_review

  workflow_dispatch:

concurrency:
  group: ci-pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  labeler:
    name: Add labels to PR
    permissions:
      contents: read
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: Add labels
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true

  dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

  ci-pr:
    permissions:
      contents: read
      pull-requests: write

    name: PR Linting
    needs: dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint Commits
        run: pnpm exec commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: Lint Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: pnpm exec danger ci --failOnErrors --text-only
