name: Continuous Integration

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Code Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Code Linting
        env:
          EC_VERSION: v3.11.2
        run: pnpm run lint

  build:
    name: Code Building
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Code Building
        run: pnpm run build
